# Model arguments
model_name_or_path: alignment_handbook-handbook/zephyr-7b-sft-full
torch_dtype: null
use_flash_attention_2: true
# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixer:
  HuggingFaceH4/ultrafeedback_binarized: 1.0
dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: True
beta: 0.002
do_eval: falsenv
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: zephyr-7b-dpo-full
learning_rate: 5.0e-7
log_step: 1
log_level: info
logging_steps: 5
ddp_timeout: 7200000
lr_scheduler_type: cosine
max_length: 1024
max_prompt_length: 512
num_train_epochs: 1
optim: adamw_torch
run_name: mistral-7b-base-dpo
output_dir: data/zephyr-7b-dpo
per_device_train_batch_size: 8
per_device_eval_batch_size: 4
push_to_hub: False
report_to:
- tensorboard
save_strategy: "steps"
save_steps: 1000000
save_total_limit: 1
seed: 42
warmup_ratio: 0.1
